=== developerworks/openempi/webapp-web/src/main/java/mpi-config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--


     Copyright (C) 2009 SYSNET International, Inc. <support@sysnetint.com>

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
     implied. See the License for the specific language governing
     permissions and limitations under the License.


-->
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:mpi="http://configuration.openempi.openhie.org/mpiconfig"
	targetNamespace="http://configuration.openempi.openhie.org/mpiconfig"
	elementFormDefault="qualified">
	<xs:element name="mpi-config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="transforms" type="mpi:transforms" minOccurs="0"/>
				<xs:element name="custom-fields" type="mpi:custom-fields" minOccurs="0"/>
				<xs:element name="blocking-configuration" type="mpi:blocking-configuration" minOccurs="0"/>
				<xs:element name="matching-configuration" type="mpi:matching-configuration" minOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="transforms">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="transform" type="mpi:transform"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="transform">
		<xs:sequence>
			<xs:element name="id" type="xs:string"/>
			<xs:element name="class" type="xs:string"/>
			<xs:element name="parameters" type="mpi:parameters" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="custom-fields">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="custom-field" type="mpi:custom-field"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="custom-field">
		<xs:sequence>
			<xs:element name="field-name" type="xs:string"/>
			<xs:element name="source-field-name" type="xs:string"/>
			<xs:element name="function" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="blocking-configuration">
		<xs:sequence>
			<xs:element name="blocking-rounds" type="mpi:blocking-rounds"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="blocking-rounds">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="blocking-round" type="mpi:blocking-round"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="blocking-round">
		<xs:sequence>
			<xs:element name="blocking-fields" type="mpi:blocking-fields"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="blocking-fields">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="blocking-field" type="mpi:blocking-field"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="blocking-field">
		<xs:sequence>
			<xs:element name="field-name" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="parameters">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="parameter" type="mpi:parameter"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="parameter">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="value" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="matching-configuration">
		<xs:sequence>
			<xs:element name="false-negative-probability" type="xs:float" minOccurs="0"/>
			<xs:element name="false-positive-probability" type="xs:float" minOccurs="0"/>
			<xs:element name="match-fields" type="mpi:match-fields"/>
			<xs:element name="config-file-directory" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="match-fields">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="match-field" type="mpi:match-field"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="match-field">
		<xs:sequence>
			<xs:element name="field-name" type="xs:string"/>
			<xs:element name="agreement-probability" type="xs:float" minOccurs="0"/>
			<xs:element name="disagreement-probability" type="xs:float" minOccurs="0"/>
			<xs:element name="string-comparator" type="xs:string" minOccurs="0"/>
			<xs:element name="match-threshold" type="xs:float" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>	
</xs:schema>

=== developerworks/openempi/core/mpi-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--


    Copyright (C) 2002-2012 "SYSNET International, Inc."
    support@sysnetint.com [http://www.sysnetint.com]

    This file is part of OpenEMPI.

    OpenEMPI is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

-->
<mpi-config xmlns="http://configuration.openempi.openhie.org/mpiconfig"
	xmlns:mpi="http://configuration.openempi.openhie.org/mpiconfig"
	xmlns:bb="http://configuration.openempi.openhie.org/basic-blocking"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://configuration.openempi.openhie.org/mpiconfig mpi-config.xsd
		http://configuration.openempi.openhie.org/basic-blocking basic-blocking.xsd">

	<global-identifier>
		<assign-global-identifier>false</assign-global-identifier>
		<namespace-identifier>2.16.840.1.113883.4.357</namespace-identifier>
		<universal-identifier>2.16.840.1.113883.4.357</universal-identifier>
		<universal-identifier-type>hl7</universal-identifier-type>
	</global-identifier>

	<transforms>
		<transform>
			<id>doubleMetaphone</id>
			<class>
				org.openhie.openempi.transformation.DoubleMetaphoneFunction
			</class>
		</transform>
	</transforms>

	<custom-fields>
		<custom-field>
			<field-name>custom1</field-name>
			<source-field-name>familyName</source-field-name>
			<function>doubleMetaphone</function>
		</custom-field>
		<custom-field>
			<field-name>custom2</field-name>
			<source-field-name>givenName</source-field-name>
			<function>doubleMetaphone</function>
		</custom-field>
	</custom-fields>

	<bb:basic-blocking>
		<bb:blocking-rounds>
			<bb:blocking-round>
				<bb:blocking-fields>
					<bb:blocking-field>
						<bb:field-name>custom1</bb:field-name>
					</bb:blocking-field>
					<bb:blocking-field>
						<bb:field-name>custom2</bb:field-name>
					</bb:blocking-field>					
				</bb:blocking-fields>
			</bb:blocking-round>
		</bb:blocking-rounds>
	</bb:basic-blocking>
	
	<matching-configuration>
		<false-negative-probability>0.2</false-negative-probability>
		<false-positive-probability>0.2</false-positive-probability>
		<match-fields>
			<match-field>
				<field-name>givenName</field-name>
				<agreement-probability>0.9</agreement-probability>
				<disagreement-probability>0.1</disagreement-probability>
				<string-comparator>JaroWinkler</string-comparator>
				<match-threshold>0.725</match-threshold>
			</match-field>
			<match-field>
				<field-name>familyName</field-name>
				<agreement-probability>0.9</agreement-probability>
				<disagreement-probability>0.1</disagreement-probability>
				<string-comparator>Levenshtein</string-comparator>
				<match-threshold>0.8125</match-threshold>
			</match-field>
			<match-field>
				<field-name>phoneNumber</field-name>
				<agreement-probability>0.9</agreement-probability>
				<disagreement-probability>0.1</disagreement-probability>
				<string-comparator>JaroWinkler</string-comparator>
				<match-threshold>0.725</match-threshold>
			</match-field>
			<match-field>
				<field-name>dateOfBirth</field-name>
				<agreement-probability>0.9</agreement-probability>
				<disagreement-probability>0.1</disagreement-probability>
				<string-comparator>JaroWinkler</string-comparator>
				<match-threshold>0.725</match-threshold>
			</match-field>
			<match-field>
				<field-name>city</field-name>
				<agreement-probability>0.9</agreement-probability>
				<disagreement-probability>0.1</disagreement-probability>
				<string-comparator>JaroWinkler</string-comparator>
				<match-threshold>0.725</match-threshold>
			</match-field>	
		</match-fields>
		<config-file-directory>D:/tmp</config-file-directory>
	</matching-configuration>
	
	<admin-configuration>
		<file-repository-directory>fileRepository</file-repository-directory>
	</admin-configuration>
</mpi-config>
